version: "3.6"
services:
  app:
    image: 'ojciedz/zderzak8300:dater-back'
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dater
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APP_ENCRYPTION_PASSWORD=${APP_ENCRYPTION_PASSWORD}
          
  db:
    image: 'postgres'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dater
    ports:
      - 5433:5432
    volumes:
    - dater_db:/var/lib/postgresql/data

volumes: 
    dater_db: